spring:
  datasource:
    url: jdbc:sqlite:./data/todo.db?foreign_keys=on
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true # 데이터 소스 초기화 시점 지연, SQL 실행 후 JPA 엔티티 데이터베이스 스키마에 맵핑
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: *****
            client-secret: *****
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

jwt:
  secret: *****
  access:
    expiration: 3600000  # 1 hour
  refresh:
    expiration: 1209600000 # 14일 (ms)
